name: Spring Boot Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Spring Boot Application
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build Application
        run: |
          chmod +x mvnw
          ./mvnw clean package

      - name: Verify JAR
        run: |
          ls -lh target/
          test -f target/my-app.jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::022499040191:role/GitHubActionsSpringBootRole
          aws-region: ap-south-1

      - name: Test AWS connection
        run: |
          aws sts get-caller-identity

      - name: Upload JAR to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws s3 cp target/my-app.jar \
            s3://${{ vars.S3_BUCKET }}/my-app.jar

          echo "JAR uploaded successfully to S3"